### Create a new User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"gihan@gmail.com",
    "password":"123456"
}

### Sign in User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"gihan@gmail.com",
    "password":"123456"
}


###Get current signed in user

GET http://localhost:3000/auth/whoami

###SignOut

POST http://localhost:3000/auth/signout

###Find with ID

GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=gihan@gmail.com

### Delete a user given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "password": "aaaaa"
}


### Color Set

GET http://localhost:3000/auth/colors/red

### color Get
GET http://localhost:3000/auth/colors